Вітаємо!

Користувацькі помилки в Solidity ідентифікуються за їх 4-байтовим 'селектором', таким же як і виклик функції. Вони піднімаються вгору по ланцюжку викликів, доки їх не зловить оператор catch в блоку try-catch, як це бачимо в функції `requestDonation()` у GoodSamaritan. З цих причин, не безпечно припускати, що помилка була викинута безпосередньо ціллю виклику контракту (тобто Wallet в цьому випадку). Будь-який інший контракт далі по ланцюжку викликів може оголосити ту саму помилку і викинути її в непередбачуваному місці, такому як функція `notify(uint256 amount)` у вашому контракті-атакувачі.
